language: java

jdk:
  - openjdk7

before_install:
  - git clone https://github.com/mpassid/shibboleth-idp-authn-shibsp
  - git checkout tags/0.9.7
  - mvn install -f shibboleth-idp-authn-shibsp/pom.xml

script:
  mvn clean package

after_failure:
  - cat target/surefire-reports/*.txt

after_success:
  - mvn clean cobertura:cobertura coveralls:report
